### ISSUE TITLE
Resource services still return 401.

### ISSUE THREAD

**Issue by JustPapi** [timtebeek/spring-security-samples#42]
I followed your tutorial on "Spring Cloud Gateway with OpenID Connect and Token Relay". I used the "spring-cloud-gateway-oidc-tokenrelay" project as a reference. My spring cloud gateway returns the login page of Keycloak once I execute an HTTP request to the gateway. After I successfully logged in, I try to make an HTTP request to one of the resource servers. But it requires a 401 error code (Unauthorized).

My project matches the configuration you have set in the example project. I'm kinda stuck here. Maybe you can point into the right direction with this problem?

Kind regards,

Pepijn

**Comment by timtebeek** [comment]
Hi Pepijn; Do get get the 401 response when accessing the resource servers through the gateway? Or are you trying to access your resource servers directly, for instance through a `curl/wget/httpie` command ?

If you're trying to access your resource servers directly you might want to have a look at the example here, which allows you to verify your resource servers independently from the gateway & keycloak: https://github.com/timtebeek/spring-security-samples/tree/master/adding-spring-security#oauth2-resource-server-configuration

Otherwise: do you also get the 401 response when you checkout a fresh copy of the project and run it as is?
https://github.com/timtebeek/spring-security-samples/tree/master/spring-cloud-gateway-oidc-tokenrelay

**Comment by JustPapi** [comment]
Hi Tim,

I used a fresh cope of one of your services. I am now able to reach the microservice via the gateway. Thanks for your fast reply. I'm going to try to the extend the resource-microservice to my needs.

Kind regards,

Pepijn

**Comment by timtebeek** [comment]
Perfect; glad I could help and good luck with extending the service to your needs!
If you have any other questions feel free to reach out.

**Comment by JustPapi** [comment]
Hi Tim,

Do you have a solution for CORS policy issues? Im trying to make requests from my angular application which runs on http://localhost:4200/. I've tried some options provided by spring security. But it brakes your gateway securityConfig.

**Comment by timtebeek** [comment]
Have you tried adding a route in the gateway to your angular application? If that's feasible, then you can have it so Angular application should not have to make any CORS requests, as you can simply call paths also routed through the gateway, with the gateway handling sign in & session.

**Comment by JustPapi** [comment]
I don't know what you are exactly are suggesting. I'm trying to figuring out whether it's possible to make request with a front-end application (Angular) to the backend with your keycloak security implementation. Im kinda stuck at this problem for the last days. I hope you can help me out.

![image](https://user-images.githubusercontent.com/28802561/84529283-7ba12980-ace1-11ea-960c-34c2e9df9358.png)

**Comment by timtebeek** [comment]
If you look here you'll see the gateway already routes a few request paths:
https://github.com/timtebeek/spring-security-samples/blob/master/spring-cloud-gateway-oidc-tokenrelay/travel-spring-cloud-gateway/src/main/resources/application.yml#L24
Now you can add another path at the end, such as:
```
      - id: angular-frontend
        uri: http://127.0.0.1:4200/
        predicates:
        - Path=/frontend/**
```
Then if you go to http://localhost:8080/frontend/ you should see you angular frontend. This frontend can also make calls through the gateway by loading `/hotels/`, or http://localhost:8080/hotels/. Notice how you're not using the hotels service port 8082, but the gateway port 8080. That's how it could work I recon.
